[package]
name = "tcprust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.13.0"
tun = "0.6.1"
tun-tap = "0.1.4"
bitflags = "1.0"
nix = { version = "0.27.1", features = ["poll"] }
